<?php
return array(
    '尉' => array('no_tone' => array('yu'), 'with_tone' => array()), 
    '戚' => array('no_tone' => array('qi', 'chi', 'chik', 'chek', 'cheok'), 'with_tone' => array()), 
    '齐' => array('no_tone' => array('qi', 'chi', 'chai', 'chai'), 'with_tone' => array()), 
    '祁' => array('no_tone' => array('qi', 'chi', 'kei'), 'with_tone' => array()), 
    '计' => array('no_tone' => array('ji', 'chi', 'kai', 'kai'), 'with_tone' => array()), 
    '纪' => array('no_tone' => array('ji', 'chi', 'kei', 'kei', 'kee', 'ki'), 'with_tone' => array()), 
    '季' => array('no_tone' => array('ji', 'chi', 'kwai', 'kuai'), 'with_tone' => array()), 
    '支' => array('no_tone' => array('zhi', 'chih', 'chi', 'tze'), 'with_tone' => array()), 
    '吉' => array('no_tone' => array('ji', 'chi', 'kut', 'kat', 'kit'), 'with_tone' => array()), 
    '嵇' => array('no_tone' => array('ji', 'chi'), 'with_tone' => array()), 
    '汲' => array('no_tone' => array('ji', 'chi'), 'with_tone' => array()), 
    '蓟' => array('no_tone' => array('ji', 'chi', 'kai'), 'with_tone' => array()), 
    '籍' => array('no_tone' => array('ji', 'chi'), 'with_tone' => array()), 
    '池' => array('no_tone' => array('chi', 'chih', 'chi', 'see', 'tee', 'tie'), 'with_tone' => array()), 
    '姬' => array('no_tone' => array('ji', 'chi', 'kei', 'kei'), 'with_tone' => array()), 
    '冀' => array('no_tone' => array('ji', 'chi', 'kei', 'kei'), 'with_tone' => array()), 
    '暨' => array('no_tone' => array('ji', 'chi'), 'with_tone' => array()), 
    '迟' => array('no_tone' => array('chi', 'chih', 'chee', 'chi', 'jee', 'ji'), 'with_tone' => array()), 
    '赵' => array('no_tone' => array('zhao', 'chao', 'chiu', 'chio', 'chow', 'jo', 'cho', 'teoh', 'chew', 'tiew'), 'with_tone' => array()), 
    '钱' => array('no_tone' => array('qian', 'chien', 'chin', 'chin', 'zee', 'joen', 'chun', 'chien', 'chen'), 'with_tone' => array()), 
    '周' => array('no_tone' => array('zhou', 'jou', 'chow', 'chou', 'chow', 'chau', 'chao', 'chew', 'ju', 'chu', 'chew', 'cheu', 'chou', 'chow', 'chiew'), 'with_tone' => array()), 
    '郑' => array('no_tone' => array('zheng', 'cheng', 'cheng', 'cheang', 'tay', 'jung', 'jeong', 'chung', 'cheong', 'ching', 'tang', 'tey', 'tay', 'tee', 'teh', 'cheng', 'chin', 'chang', 'chung', 'chiang'), 'with_tone' => array()), 
    '陈' => array('no_tone' => array('chen', 'chen', 'chan', 'chan', 'tan', 'chan', 'ting', 'jin', 'chin', 'chan', 'chin', 'chen', 'tan', 'tang', 'ting', 'ding', 'sin'), 'with_tone' => array()), 
    '蒋' => array('no_tone' => array('jiang', 'chiang', 'cheung', 'cheong', 'jang', 'chang', 'chiang', 'cheong', 'chiong'), 'with_tone' => array()), 
    '秦' => array('no_tone' => array('qin', 'chin', 'chun', 'jin', 'chin', 'chin', 'ch\'ng'), 'with_tone' => array()), 
    '金' => array('no_tone' => array('jin', 'chin', 'kam', 'kam', 'kim', 'kim', 'king'), 'with_tone' => array()), 
    '姜' => array('no_tone' => array('jiang', 'chiang', 'keung', 'keong', 'kang', 'gang', 'khiang', 'kiang'), 'with_tone' => array()), 
    '谢' => array('no_tone' => array('xie', 'hsieh', 'tse', 'che', 'cheah', 'tay', 'chia', 'sa', 'cheah', 'chiah', 'chia', 'seah', 'sia', 'see'), 'with_tone' => array()), 
    '靳' => array('no_tone' => array('jin', 'chin', 'kan'), 'with_tone' => array()), 
    '菁' => array('no_tone' => array('jing', 'ching', 'ching'), 'with_tone' => array()), 
    '肖' => array('no_tone' => array('xiao', 'hsiao', 'chiu'), 'with_tone' => array()), 
    '展' => array('no_tone' => array('zhan', 'chan', 'chin'), 'with_tone' => array()), 
    '占' => array('no_tone' => array('zhan', 'chan', 'chim'), 'with_tone' => array()), 
    '战' => array('no_tone' => array('zhan', 'chan', 'chin'), 'with_tone' => array()), 
    '席' => array('no_tone' => array('xi', 'hsi', 'tsik', 'chik', 'chek'), 'with_tone' => array()), 
    '强' => array('no_tone' => array('qiang', 'chiang', 'keung', 'keong'), 'with_tone' => array()), 
    '贾' => array('no_tone' => array('jia', 'chia', 'ka', 'kar', 'ka'), 'with_tone' => array()), 
    '江' => array('no_tone' => array('jiang', 'chiang', 'kong', 'kong', 'kang', 'kang', 'kong', 'khong', 'khang'), 'with_tone' => array()), 
    '邱' => array('no_tone' => array('qiu', 'chiu', 'yau', 'iao', 'iau', 'khoo', 'khu', 'kue', 'khor', 'kiew', 'kiu'), 'with_tone' => array()), 
    '经' => array('no_tone' => array('jing', 'ching', 'king', 'keng', 'gin'), 'with_tone' => array()), 
    '裘' => array('no_tone' => array('qiu', 'chiu', 'kau', 'kao'), 'with_tone' => array()), 
    '程' => array('no_tone' => array('cheng', 'cheng', 'ching', 'cheng', 'tiah', 'tiang'), 'with_tone' => array()), 
    '家' => array('no_tone' => array('jia', 'chia', 'ka', 'kah', 'ka'), 'with_tone' => array()), 
    '井' => array('no_tone' => array('jing', 'ching'), 'with_tone' => array()), 
    '焦' => array('no_tone' => array('jiao', 'chiao', 'chiu', 'chio'), 'with_tone' => array()), 
    '秋' => array('no_tone' => array('qiu', 'chiu', 'chau', 'chao'), 'with_tone' => array()), 
    '仇' => array('no_tone' => array('qiu', 'chiu', 'sau', 'sao', 'chiu'), 'with_tone' => array()), 
    '景' => array('no_tone' => array('jing', 'ching', 'king', 'keng'), 'with_tone' => array()), 
    '詹' => array('no_tone' => array('zhan', 'chan', 'jim', 'tsim', 'chim', 'chim'), 'with_tone' => array()), 
    '乔' => array('no_tone' => array('qiao', 'chiao', 'kiu', 'kio'), 'with_tone' => array()), 
    '郏' => array('no_tone' => array('jia', 'chia'), 'with_tone' => array()), 
    '莊' => array('no_tone' => array('zhuang', 'chuang', 'chong', 'chuang', 'ching', 'chin', 'ch\'ng'), 'with_tone' => array()), 
    '曾' => array('no_tone' => array('zeng', 'cheng', 'tseng', 'tsang', 'chang', 'tjan', 'tjan', 'chang', 'chan', 'chin'), 'with_tone' => array()), 
);